### ISSUE TITLE
[WEB][DRAFT][25 meters] Avoid nexted loop in FRONTEND

### ISSUE THREAD

**Issue by Adouni** [green-code-initiative/ecoCode-challenge#12]
# Efficient code: Avoid high level of nested loops
## Platform
| OS | OS version | Langage |
|---------------|--------------|------------|
| - | - | Javascript|
## Main caracteristics
| ID | Title | Category | Sub-category |
|----------|----------------------|-------------|----------------|
| {id} | {title} | {Category} | {SubCategory} |
## Severity / Remediation Cost
| Severity | Remediation Cost |
|------------|---------------------|
| Minor | Medium |

## Rule short description
Usings lots of levels of nested loops may result in useless processing.

## Text
Nested loops are frequently (but not always) bad practice, because they're frequently (but not always) overkill for what you're trying to do.
In many cases, there's a much faster and less wasteful way to accomplish the goal you're trying to achieve.
It is usually better to break this code into smaller functions.

## HTML
for(var i = 1; i &lt;= 100; i++)
{
  for(var j = 1; j &lt;= 100; j++)
  {
     for(var j = 1; j &lt;= 100; j++)
      {
         statement2; // It will execute 1000000 times.
     }
  }
}

## Implementation principle
Detect nested loops when loop depth exceeds X
X being a configurable value. Default to 4?

**Comment by olegoaer** [comment]
This classic code smell is already managed by quality tools.
See https://blog.jetbrains.com/idea/2017/08/code-smells-deeply-nested-code/
