### ISSUE TITLE
[DRAFT] [Web] [23cm] Drop libraries that are natively provided

### ISSUE THREAD

**Issue by yciabaud** [green-code-initiative/ecoCode-challenge#26]
We can enforce removal of obsolete libraries in favor of native implementation like jQuery 

Team 23cm

**Comment by utarwyn** [comment]
Hello 👋

I think this rule is more or less related to #37: the main idea is to detect a list of dependencies you shouldn't use: either replace them, or remove them entirely. Very good idea, thank you!

I suggest continuing the discussion in the other ticket if that's okay,
Regards
