### ISSUE TITLE
[iOS][ANDROID] Avoid unnecessary background actions or loop

### ISSUE THREAD

**Issue by lleprestreonepoint** [green-code-initiative/ecoCode-challenge#30]
Language : Swift, Kotlin, Java, Obj-C, Obj-C++, React Native, Flutter

There are event listeners for when the application goes into the background. Then, a callback is triggered and the developer can execute the code they want.
It is recommended to avoid performing expensive actions (such as using location and making API calls) or making a loop when the application goes into the background.

Team 23

**Comment by olegoaer** [comment]
Interesting idea in principle, but lacks concrete examples for each platform. Also, there is no clear definition of what an "expensive action" is. 
We can't flag every method call made in the background.
