### ISSUE TITLE
[23CM][Draft][Android] Avoid nesting of layout (23cm)

### ISSUE THREAD

**Issue by raphael-beck** [green-code-initiative/ecoCode-challenge#33]
Rendering layouts in Android use the GPU. Nesting layouts will cost a lot of GPU and thus battery

Team 23cm

**Comment by olegoaer** [comment]
This smell is already detected by the built-in linter of Android Studio : https://googlesamples.github.io/android-custom-lint-rules/checks/TooDeepLayout.md.html

In addition, even if we understand the general idea, the Google team classified it as a **performance** issue (refer to my keynote here ;)

**Comment by raphael-beck** [comment]
Ok I get it. 
The issue could be closed then.

Maybe some rules from the linter could be copied into sonar ecocode plugin rules as they are relevant and possibly not everyone use android studio :)
