### ISSUE TITLE
[WEB][30GR][DRAFT] optimize use of lodash or underscore (BP040)

### ISSUE THREAD

**Issue by titiBeOne** [green-code-initiative/ecoCode-challenge#35]
# remove dependencies outdated (BP040)

## Platform

|   OS          |  OS version  |  Langage   |
|---------------|--------------|------------|
| -             | -            | JS         |

## Main caracteristics

|   ID     | Title                                | Category      | Sub-category   |
|----------|--------------------------------------|---------------|----------------|
| CRDOMxxx | Remove dependencies outdated         | Best Practice | -              |

## Severity / Remediation Cost

- **Case 1**: in js there is a lot of dependancy outdated with some vulnerabilities and there some eslint rules 
https://github.com/dependency-check/dependency-check-sonar-plugin
  
|  Severity  | Remediation Cost    |
|------------|---------------------|
| Hight      | Hight               |

- **Case 2** : Identity and remove the outdated library.

|  Severity  | Remediation Cost    |
|------------|---------------------|
| Hight      | Hight                 |

## Rule short description

- **Case 1**: Identify the outdated library

## Text

:recycle: There is a lot of dependency outdated and don't necessary to be used, integrate a dependency checker that list the dependency which contain some vulnerability : 
https://github.com/dependency-check/dependency-check-sonar-plugin
this plugin is based on OWASP ressources : https://owasp.org/www-project-dependency-check/

## Benefits

Remove useless library

## Implementation principle

- [ ] https://github.com/dependency-check/dependency-check-sonar-plugin
- [ ] https://owasp.org/www-project-dependency-check/

**Comment by utarwyn** [comment]
Hello 👋  Thank you for the proposal.
This rule has been implemented in ecoCode-javascript plugin! ([documentation here](https://github.com/green-code-initiative/ecoCode-javascript/blob/main/eslint-plugin/docs/rules/no-import-all-from-library.md))
