### ISSUE TITLE
[Android] Limit number of dependencies for an application

### ISSUE THREAD

**Issue by tdeffains** [green-code-initiative/ecoCode-challenge#42]
# Optimized API: limit number of dependencies for an application
## Platform
| OS | OS version | Langage |
|----------|------------|-----------|
| Android | - | Gradle |
## Main caracteristics
| ID | Title | Category | Sub-category |
|---------|----------------------------------|-------------|----------------|
| - | limit number of dependencies for an application | Optimized API | Limit third-party dependencies |
## Severity / Remediation Cost
| Severity | Remediation Cost |
|----------|------------------|
| - | - |
## Rule short description
It is good practice to limit the number of dependencies for an application.
### Text
Embedding dependency may add unnecessary weight to your application. Plus it can embed dangerous flags that you don't want inside your app.
### build.gradle
```gradle
dependencies {
    // Dependency on a local library module
    implementation project(':mylibrary')

    // Dependency on local binaries
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // Dependency on a remote binary
    implementation 'com.example.android:app-magic:12.3'
}
https://developer.android.com/studio/build/dependencies
```
## Implementation principle
- Extract all **_build.gradle_** files (there may be several ones if app is modularized)
- For each **_build.gradle_** file extract _**dependencies {}**_ bloc
- Count number of _**implementation**_ lines **except** if:
   - followed by **_project_** (internal dependency)
   - library starts with (Official Google libraries - relates to Hidden Tracker Risk rule)
      - **_android._**
      - **_androidx._**
      - **_com.android._**
      - **_com.google._**

## To be defined (open discussion)
What is the recommendation for external dependencies? (we can checl several popular GitHub repositories for Android applications GitHub and determine average of external dependencies)
Also this amount of external dependencies depends on application code size. For example 10 libraries may be too much for a small app but 30 may not for a huge app.
Which criteria for app code size? --> number of Java lines or Java classes

**Comment by olegoaer** [comment]
Interesting but undecidable criterion.
