### ISSUE TITLE
[Team169Cibles][Android] Sobriety: animation-free (Lottie library and imports of Android Animation or Jetpack Compose API)

### ISSUE THREAD

**Issue by tdeffains** [green-code-initiative/ecoCode-challenge#43]
# Sobriety: animation-free (Lottie library and imports of Android Animation or Jetpack Compose API)
## Platform
| OS | OS version | Langage |
|----------|------------|-----------|
| Android | - | Gradle/Java/Kotlin |
## Main caracteristics
| ID | Title | Category | Sub-category |
|---------|----------------------------------|-------------|----------------|
| - | Lottie library and imports of Android Animation or Jetpack Compose API | Sobriety | animation-free |
## Severity / Remediation Cost
| Severity | Remediation Cost |
|----------|------------------|
| - | - |
## Rule short description
Animations isn't ecofriendly for saving battery power
### Text
Lottie is a commonly used library for embedding animations
https://github.com/airbnb/lottie-android
Animation implementation requires to import Android classes
https://developer.android.com/reference/android/animation/Animator
https://developer.android.com/reference/android/view/animation/Animation
Jetpack Compose is the new Google framework for Android UI and provides APIs for animations
https://developer.android.com/reference/kotlin/androidx/compose/animation/package-summary
### build.gradle
```gradle
dependencies {
    //Animations Lottie
    implementation 'com.airbnb.android:lottie:[x.y.z]'
}
```
### Java files
```Java
import android.animation.*
import android.view.animation.*
```
### Kotlin files
```Kotlin
import androidx.compose.animation.*
```
### Lottie library
- Extract all **_build.gradle_** files (there may be several ones if app is modularized)
- For each **_build.gradle_** file extract _**dependencies {}**_ bloc
- Check if there is _**implementation**_ line for **_com.airbnb.android:lottie_**
   - followed by **_project_** (internal dependency)
   - library starts with (Official Google libraries - relates to Hidden Tracker Risk rule)
      - **_android._**
      - **_androidx._**
      - **_com.android._**
      - **_com.google._**
### Animation imports
- Check in all Java files for **_android.animation_** imports
- Check in all Java files for **_android.view.animation_** imports
### Jetpack Compose imports
- Check in all Kotlin files for **_androidx.compose.animation_** imports
**Pre-requisite:** for this rule we need to have Kotlin analyzer

**Comment by olegoaer** [comment]
Obviously a good practice, but the ecocode plugin must focus on detection of built-in animations. Taking into account the countless third-party animation libraries is too cumbersome.
