### ISSUE TITLE
Improve test documentation

### ISSUE THREAD

**Issue by vimarie** [green-code-initiative/ecoCode-challenge#48]
Add a schema to explain how it works to explain the interaction between the test and the test files and also some doc about the magic comment "// Noncompliant {{Avoid getting the size of the collection in the loop}}"

**Comment by utarwyn** [comment]
Hello 👋 
I don't think this issue refers to a rule idea? Perhaps you can reopen a ticket in the repositories of the plugins concerned, if you consider that this improvement still needs to be made.

I close the issue,
Regards
