### ISSUE TITLE
[iOS][Android] Detect tech updates that generate incompatibilities or lead to equipment renewal

### ISSUE THREAD

**Issue by PierreEc** [green-code-initiative/ecoCode-challenge#50]
You can verify the minimum version of SDK used on android and the target version of iOS, iPadOS, watchOS and tvOS on apple platform.

Easy implementable:
The information is in config files and you should have a minimum default value that could be customized according to your organization. 
Recommandation:
If you want to change the default value, you should measure which versions are used by your target customers

**Comment by PierreEc** [comment]
# Detect tech updates that generate incompatibilities or lead to equipment renewal

## Platform
|                          OS                                       | OS version |     Langage.     |
|---------------------------------------- |------------ |---------------|
|   iOS/iPadOS/WatchOS/tvOS - Android    |           -        |  Swift / Kotlin  |


## Main caracteristics

|   ID      | Title                            | Category    | Sub-category   |
| ------ |----------------------------------|-------------|----------------|
|    -       |   | Environment | Optimized API  |

## Severity / Remediation Cost

| Severity | Remediation Cost |
|----------|------------------|
| Medium    | Minor            |

## Rule short description

You can verify the minimum version of SDK used on android and the target version of iOS, iPadOS, watchOS and tvOS on apple platform.


## Rule complete description

### Text

You can verify the minimum version of SDK used on android and the target version of iOS, iPadOS, watchOS and tvOS on apple platform.

### HTML

```html
<p>You can verify the minimum version of SDK used on android and the target version of iOS, iPadOS, watchOS and tvOS on apple platform.</p>
<p>
The information is in config files and you should have a minimum default value that could be customized according to your organization.
<u>Recommandation:</u>
If you want to change the default value, you should measure which versions are used by your target customers
</p>

```

## Implementation principle

- In pbxproj file on apple platform on variable "IPHONEOS_DEPLOYMENT_TARGET"
- In config file on android. Varible "minSdk"

**Comment by olegoaer** [comment]
Related to [this issue](https://github.com/green-code-initiative/ecoCode-challenge/issues/40)
