### ISSUE TITLE
[WEB][30GR][Draft] Use picture element to choose the most relevant image compression method

### ISSUE THREAD

**Issue by titiBeOne** [green-code-initiative/ecoCode-challenge#53]
# Use picture element to choose the most relevant image compression method

## Platform

|   OS          |  OS version  |  Langage   |
|---------------|--------------|------------|
| -             | -            | HTML       |

## Main caracteristics

|   ID     | Title                                                                    | Category      | Sub-category          |
|----------|--------------------------------------------------------------------------|---------------|-----------------------|
| CRDOMxxx | Use picture element to choose the most relevant image compression method | Best Practice | Network Optimization  |

## Severity / Remediation Cost

|  Severity  | Remediation Cost    |
|------------|---------------------|
| Minor      | Minor               |

## Rule short description

- **Case 1** : Use picture element to choose the most relevant image compression method

## Text

avif / webp are new compression algorithms; the `picture` element allows to use the best compression algorithm to deliver an image, depending on the capabilities of the browser.

Source: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

## HTML
```html
<picture>
  <source srcset="photo.avif" type="image/avif" />
  <source srcset="photo.webp" type="image/webp" />
  <img src="photo.jpg" alt="photo" />
</picture>
```

## Implementation principle

- [ ] Use the `picture` element https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

**Comment by utarwyn** [comment]
Hello! Thank you for the proposal. This rule has been accepted and is now part of the ecoCode rule repository and now needs to be implemented (at the next challenge, perhaps?).

Check https://github.com/green-code-initiative/ecoCode/pull/269
