### ISSUE TITLE
[Java][Team 2 millions] Use of Entity in Rest controller

### ISSUE THREAD

**Issue by JulienPlanque** [green-code-initiative/ecoCode-challenge#58]
# Optimized API: Use of Entity in Rest controller 
## Platform
| OS | OS version | Langage |
|----------|------------|-----------|
| - | - | Java |
## Main caracteristics
| ID | Title | Category | Sub-category |
|---------|----------------------------------|-------------|----------------|
??? | Use of Entity in Rest controller | Environment | Optimized API |
## Severity / Remediation Cost
| Severity | Remediation Cost |
|----------|------------------|
| Minor | Minor |
## Rule short description
Using persistence Entity in the return of a Rest controler is not
energy efficient. This use induces a multiples unnecessary SQL calls, multiple unused fields serialization,
and thus unnecessary calculations by the CPU, RAM usage and network usage.
### Text
Using persistence Entity, class with @Entity annotation of javax.persistence is not
energy efficient.
Prefer the usage of Data Transfert Object (DTO) which is more energy friendly. This reduces the amount of information returned so that it is more relevant and lighter.

```html
<p>Using persistence Entity in the return of a Rest controler is not
energy efficient. This use induces a multiples unnecessary SQL calls, multiple unused fields serialization,
and thus unnecessary calculations by the CPU, RAM usage and network usage. </p>
<h2>Noncompliant</h2>
<pre>
	@RestController
    public class AvoidReturningSpringEntityInRestController {
        private final BookService bookService;

        public AvoidReturningSpringEntityInRestController(BookService bookstoreService) {
            this.bookService = bookstoreService;
        }

        @RequestMapping("books")
        public List<Book> findBooks() {
        return bookService.findAll();
        }
    }

    @Entity
    public class Books {
        // Attributes of books
    }
</pre>
<h2>Compliant Solution</h2>
<pre>
    @RestController
    public class AvoidReturningSpringEntityInRestController {
        private final BookService bookService;

        public AvoidReturningSpringEntityInRestController(BookService bookstoreService) {
            this.bookService = bookstoreService;
        }

        @RequestMapping("books")
        public List<BookDTO> findBooks() {
            return BookMapper.from(bookService.findAll());
        }
    }
</pre>
```

## Implementation principle
- Inspect the all classes with @RestController annotation
- Inpect in all method the class in return, directly or in a collection
- If this class has @Entity annotation of javax.persistence, report the line

**Comment by JulienPlanque** [comment]
Build by Teams 2 millions

**Comment by dedece35** [comment]
Hi @MP-Aubay, @JulienPlanque 

sorry but with implementation is that situation, we can't accept this implementation because : 
- no scientific paper to prove this rule
- no measures to prove it's a "green" rule

We keep this proposition to measure it when we will have a tool to measure it.
(check [RULES.md](https://github.com/green-code-initiative/ecoCode/blob/main/RULES.md#rules-to-be-reworked--measured--clarified) )
