### ISSUE TITLE
JS - Use official social media sharing buttons

### ISSUE THREAD

**Issue by julessanglier** [green-code-initiative/ecoCode-challenge#90]
**Is your feature request related to a problem? Please describe.**
These JavaScript plugins are very resource-intensive: to work, they require a large number of requests and download heavy files. It is better to prefer direct links.

**Comment by jhertout** [comment]
Even if the subject might be interesting, I am not sure we should keep this issue open. With the lack of information and without responses, I think we should close this kind of issues. What do you think @utarwyn?

**Comment by utarwyn** [comment]
Hello @jhertout, I agree 👍
